#include "http_server_ux_enhanced.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "string.h"

static const char *TAG = "http_server_files";

// 简化版机器人编程界面 - 确保完整性和功能性
static const char robot_sequence_html[] = 
"<!DOCTYPE html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n"
"    <title>翅膀控制系统 - 机器人编程</title>\n"
"    <style>\n"
"        * {box-sizing: border-box;}\n"
"        body {font-family: Arial, sans-serif; margin: 0; padding: 15px; background-color: #fff34d; color: #333; font-size: 14px;}\n"
"        .container {max-width: 1080px; margin: 0 auto;}\n"
"        h1 {text-align: center; color: #2c3e50; margin-bottom: 20px; font-size: 24px; font-weight: bold;}\n"
"        .section {background: white; border-radius: 12px; padding: 16px; margin-bottom: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);}\n"
"        .section-title {font-size: 18px; font-weight: bold; margin-bottom: 12px; color: #2c3e50; text-align: center;}\n"
"        input[type=\"range\"] {width: 100%; height: 8px; border-radius: 4px; background: #ddd; outline: none; -webkit-appearance: none; margin: 4px 0;}\n"
"        input[type=\"number\"] {width: 100%; padding: 8px; border: 2px solid #ddd; border-radius: 8px; font-size: 14px;}\n"
"        .button-group {display: flex; gap: 8px; flex-wrap: wrap; margin: 8px 0;}\n"
"        button {flex: 1; min-width: 70px; padding: 10px; border: none; border-radius: 20px; background: #3498db; color: white; font-weight: bold; cursor: pointer;}\n"
"        .hidden {display: none !important;}\n"
"        .feedback {margin-top: 8px; padding: 6px; border-radius: 6px; text-align: center; font-weight: bold;}\n"
"    </style>\n"
"</head>\n"
"<body onload=\"init()\">\n"
"    <div class=\"container\">\n"
"        <h1>🦋 翅膀控制系统 - 机器人编程</h1>\n"
"        \n"
"        <!-- 控制设置 -->\n"
"        <div class=\"section\">\n"
"            <div class=\"section-title\">⚙️ 控制设置</div>\n"
"            <div>\n"
"                <label>最小角度限制 (°)</label>\n"
"                <input type=\"number\" id=\"min-angle\" value=\"120\" min=\"0\" max=\"270\">\n"
"            </div>\n"
"            <div>\n"
"                <label>最大角度限制 (°)</label>\n"
"                <input type=\"number\" id=\"max-angle\" value=\"150\" min=\"0\" max=\"270\">\n"
"            </div>\n"
"            <button onclick=\"updateAngleLimits()\" style=\"background: #27ae60;\">更新角度限制</button>\n"
"            <div id=\"limits-feedback\" class=\"feedback\"></div>\n"
"            <div>\n"
"                <label><input type=\"checkbox\" id=\"symmetric-lock\" checked onchange=\"toggleSymmetricMode()\"> 左右对称控制</label>\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <!-- 舵机控制 - 双滑条模式 -->\n"
"        <div class=\"section\" id=\"dual-servo-control\">\n"
"            <div class=\"section-title\">🦾 舵机控制 (独立)</div>\n"
"            <div>\n"
"                <label>左侧翅膀角度</label>\n"
"                <input type=\"range\" id=\"left-servo\" min=\"120\" max=\"150\" value=\"135\" oninput=\"updateDualAngle('left')\">\n"
"                <span id=\"left-angle-value\">135°</span>\n"
"                <label>左侧速度 (ms)</label>\n"
"                <input type=\"number\" id=\"left-speed\" value=\"1000\" min=\"0\" max=\"9999\" onchange=\"updateDualSpeed('left')\">\n"
"            </div>\n"
"            <div>\n"
"                <label>右侧翅膀角度</label>\n"
"                <input type=\"range\" id=\"right-servo\" min=\"120\" max=\"150\" value=\"135\" oninput=\"updateDualAngle('right')\">\n"
"                <span id=\"right-angle-value\">135°</span>\n"
"                <label>右侧速度 (ms)</label>\n"
"                <input type=\"number\" id=\"right-speed\" value=\"1000\" min=\"0\" max=\"9999\" onchange=\"updateDualSpeed('right')\">\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <!-- 舵机控制 - 单滑条模式 -->\n"
"        <div class=\"section hidden\" id=\"single-servo-control\">\n"
"            <div class=\"section-title\">🦾 舵机控制 (对称)</div>\n"
"            <div>\n"
"                <label>两侧翅膀角度</label>\n"
"                <input type=\"range\" id=\"both-servo\" min=\"120\" max=\"150\" value=\"135\" oninput=\"updateSingleAngle()\">\n"
"                <span id=\"both-angle-value\">135°</span>\n"
"                <label>两侧速度 (ms)</label>\n"
"                <input type=\"number\" id=\"both-speed\" value=\"1000\" min=\"0\" max=\"9999\" onchange=\"updateSingleSpeed()\">\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <!-- 电机控制 -->\n"
"        <div class=\"section\">\n"
"            <div class=\"section-title\">⚡ 电机控制</div>\n"
"            <div class=\"button-group\">\n"
"                <button class=\"motor-button\" style=\"background: #e74c3c;\" onclick=\"motorAction('expand')\">展开翅膀</button>\n"
"                <button class=\"motor-button\" style=\"background: #e74c3c;\" onclick=\"motorAction('close')\">收拢翅膀</button>\n"
"                <button class=\"motor-button\" style=\"background: #e74c3c;\" onclick=\"motorAction('reset')\">重置位置</button>\n"
"                <button class=\"motor-button\" style=\"background: #e74c3c;\" onclick=\"motorAction('stop')\">停止电机</button>\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <!-- 机器人编程序列控制 -->\n"
"        <div class=\"section\">\n"
"            <div class=\"section-title\">🤖 机器人编程</div>\n"
"            <div class=\"button-group\">\n"
"                <button class=\"record-button\" style=\"background: #e67e22;\" onclick=\"startRecording()\" id=\"start-record-btn\">⏺️ 开始录制</button>\n"
"                <button class=\"record-button\" style=\"background: #e67e22;\" onclick=\"stopRecording()\" id=\"stop-record-btn\" disabled>⏹️ 停止录制</button>\n"
"            </div>\n"
"            <div id=\"recording-status\">等待开始录制...</div>\n"
"            <div class=\"button-group\">\n"
"                <button class=\"record-button\" style=\"background: #e67e22;\" onclick=\"recordCurrentStep()\" id=\"record-step-btn\" disabled>📝 记录步骤</button>\n"
"                <button class=\"undo-button\" style=\"background: #7f8c8d;\" onclick=\"undoLastStep()\" id=\"undo-btn\" disabled>↩️ 撤回</button>\n"
"            </div>\n"
"            <div>已记录 <span id=\"step-count\">0</span> 步</div>\n"
"            <div class=\"button-group\">\n"
"                <button class=\"sequence-button\" style=\"background: #9b59b6;\" onclick=\"setDefaultSequence()\">🔄 默认开合</button>\n"
"                <button class=\"sequence-button\" style=\"background: #9b59b6;\" onclick=\"clearAllSteps()\">🗑️ 清空序列</button>\n"
"            </div>\n"
"            <div>\n"
"                <label>当前序列步骤:</label>\n"
"                <div id=\"steps-list\">暂无步骤</div>\n"
"            </div>\n"
"            <div class=\"button-group\">\n"
"                <button class=\"sequence-button\" style=\"background: #9b59b6;\" onclick=\"playSequence()\">▶️ 播放序列</button>\n"
"                <button class=\"sequence-button\" style=\"background: #e74c3c;\" onclick=\"stopPlaySequence()\">⏹️ 停止播放</button>\n"
"            </div>\n"
"            <div id=\"sequence-status\" class=\"feedback\"></div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        let minAngle = 120;\n"
"        let maxAngle = 150;\n"
"        let symmetricMode = true;\n"
"        let isRecording = false;\n"
"        let stepCount = 0;\n"
"        \n"
"        function init() {\n"
"            updateSliderRanges();\n"
"            toggleSymmetricMode();\n"
"            updateRecordingUI();\n"
"            loadSequenceSteps();\n"
"        }\n"
"        \n"
"        function updateSliderRanges() {\n"
"            const sliders = ['left-servo', 'right-servo', 'both-servo'];\n"
"            sliders.forEach(id => {\n"
"                const slider = document.getElementById(id);\n"
"                if (slider) {\n"
"                    slider.min = minAngle;\n"
"                    slider.max = maxAngle;\n"
"                    const currentValue = parseInt(slider.value);\n"
"                    if (currentValue < minAngle) slider.value = minAngle;\n"
"                    if (currentValue > maxAngle) slider.value = maxAngle;\n"
"                }\n"
"            });\n"
"        }\n"
"        \n"
"        function updateAngleLimits() {\n"
"            const newMin = parseInt(document.getElementById('min-angle').value);\n"
"            const newMax = parseInt(document.getElementById('max-angle').value);\n"
"            \n"
"            if (newMin >= 0 && newMin <= 270 && newMax >= 0 && newMax <= 270 && newMin < newMax) {\n"
"                minAngle = newMin;\n"
"                maxAngle = newMax;\n"
"                updateSliderRanges();\n"
"                fetch('/set_limits?min=' + minAngle + '&max=' + maxAngle)\n"
"                    .then(() => {\n"
"                        document.getElementById('limits-feedback').textContent = '✓ 角度范围已更新';\n"
"                        document.getElementById('limits-feedback').style.color = '#27ae60';\n"
"                    });\n"
"            } else {\n"
"                document.getElementById('limits-feedback').textContent = '❌ 角度范围无效！';\n"
"                document.getElementById('limits-feedback').style.color = '#e74c3c';\n"
"                document.getElementById('min-angle').value = minAngle;\n"
"                document.getElementById('max-angle').value = maxAngle;\n"
"            }\n"
"        }\n"
"        \n"
"        function toggleSymmetricMode() {\n"
"            symmetricMode = document.getElementById('symmetric-lock').checked;\n"
"            \n"
"            if (symmetricMode) {\n"
"                document.getElementById('dual-servo-control').classList.add('hidden');\n"
"                document.getElementById('single-servo-control').classList.remove('hidden');\n"
"                \n"
"                const leftValue = parseInt(document.getElementById('left-servo').value);\n"
"                document.getElementById('both-servo').value = leftValue;\n"
"                document.getElementById('both-angle-value').textContent = leftValue + '°';\n"
"                \n"
"                const speed = parseInt(document.getElementById('both-speed').value);\n"
"                fetch('/set_servo?servo_id=0&angle=' + leftValue + '&speed=' + speed);\n"
"                fetch('/set_servo?servo_id=1&angle=' + leftValue + '&speed=' + speed);\n"
"            } else {\n"
"                document.getElementById('single-servo-control').classList.add('hidden');\n"
"                document.getElementById('dual-servo-control').classList.remove('hidden');\n"
"                \n"
"                const bothValue = parseInt(document.getElementById('both-servo').value);\n"
"                document.getElementById('left-servo').value = bothValue;\n"
"                document.getElementById('right-servo').value = bothValue;\n"
"                document.getElementById('left-angle-value').textContent = bothValue + '°';\n"
"                document.getElementById('right-angle-value').textContent = bothValue + '°';\n"
"            }\n"
"        }\n"
"        \n"
"        function updateSingleAngle() {\n"
"            const angle = parseInt(document.getElementById('both-servo').value);\n"
"            const speed = parseInt(document.getElementById('both-speed').value);\n"
"            \n"
"            fetch('/set_servo?servo_id=0&angle=' + angle + '&speed=' + speed);\n"
"            fetch('/set_servo?servo_id=1&angle=' + angle + '&speed=' + speed);\n"
"            \n"
"            document.getElementById('both-angle-value').textContent = angle + '°';\n"
"        }\n"
"        \n"
"        function updateDualAngle(side) {\n"
"            const slider = document.getElementById(side + '-servo');\n"
"            const angle = parseInt(slider.value);\n"
"            const speed = parseInt(document.getElementById(side + '-speed').value);\n"
"            const servoId = side === 'left' ? 0 : 1;\n"
"            \n"
"            fetch('/set_servo?servo_id=' + servoId + '&angle=' + angle + '&speed=' + speed);\n"
"            document.getElementById(side + '-angle-value').textContent = angle + '°';\n"
"        }\n"
"        \n"
"        function motorAction(action) {\n"
"            fetch('/motor?action=' + action);\n"
"        }\n"
"        \n"
"        function updateRecordingUI() {\n"
"            const startBtn = document.getElementById('start-record-btn');\n"
"            const stopBtn = document.getElementById('stop-record-btn');\n"
"            const recordBtn = document.getElementById('record-step-btn');\n"
"            const undoBtn = document.getElementById('undo-btn');\n"
"            const statusDiv = document.getElementById('recording-status');\n"
"            \n"
"            if (isRecording) {\n"
"                startBtn.disabled = true;\n"
"                stopBtn.disabled = false;\n"
"                recordBtn.disabled = false;\n"
"                statusDiv.textContent = '录制中...';\n"
"                statusDiv.style.color = '#e74c3c';\n"
"            } else {\n"
"                startBtn.disabled = false;\n"
"                stopBtn.disabled = true;\n"
"                recordBtn.disabled = true;\n"
"                statusDiv.textContent = '等待开始录制...';\n"
"                statusDiv.style.color = '#7f8c8d';\n"
"            }\n"
"            \n"
"            undoBtn.disabled = (stepCount <= 0);\n"
"            document.getElementById('step-count').textContent = stepCount;\n"
"        }\n"
"        \n"
"        function startRecording() {\n"
"            fetch('/sequence/start')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (data.success) {\n"
"                        isRecording = true;\n"
"                        stepCount = data.frame_count || 0;\n"
"                        updateRecordingUI();\n"
"                        document.getElementById('sequence-status').textContent = '✅ 录制已开始';\n"
"                        document.getElementById('sequence-status').style.color = '#27ae60';\n"
"                        loadSequenceSteps();\n"
"                    } else {\n"
"                        document.getElementById('sequence-status').textContent = '❌ ' + data.message;\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    }\n"
"                });\n"
"        }\n"
"        \n"
"        function stopRecording() {\n"
"            fetch('/sequence/stop')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (data.success) {\n"
"                        isRecording = false;\n"
"                        stepCount = data.frame_count || 0;\n"
"                        updateRecordingUI();\n"
"                        document.getElementById('sequence-status').textContent = '⏹️ 录制已停止';\n"
"                        document.getElementById('sequence-status').style.color = '#7f8c8d';\n"
"                    } else {\n"
"                        document.getElementById('sequence-status').textContent = '❌ ' + data.message;\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    }\n"
"                });\n"
"        }\n"
"        \n"
"        function recordCurrentStep() {\n"
"            if (!isRecording) {\n"
"                document.getElementById('sequence-status').textContent = '⚠️ 请先开始录制';\n"
"                document.getElementById('sequence-status').style.color = '#f39c12';\n"
"                return;\n"
"            }\n"
"            \n"
"            let leftAngle, rightAngle;\n"
"            if (symmetricMode) {\n"
"                leftAngle = parseInt(document.getElementById('both-servo').value);\n"
"                rightAngle = leftAngle;\n"
"            } else {\n"
"                leftAngle = parseInt(document.getElementById('left-servo').value);\n"
"                rightAngle = parseInt(document.getElementById('right-servo').value);\n"
"            }\n"
"            \n"
"            fetch(`/sequence/record?left_angle=${leftAngle}&right_angle=${rightAngle}`)\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (data.success) {\n"
"                        stepCount = data.frame_count || stepCount + 1;\n"
"                        updateRecordingUI();\n"
"                        document.getElementById('sequence-status').textContent = `✅ 步骤${stepCount}已记录`;\n"
"                        document.getElementById('sequence-status').style.color = '#27ae60';\n"
"                        loadSequenceSteps();\n"
"                    } else {\n"
"                        document.getElementById('sequence-status').textContent = '❌ ' + data.message;\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    }\n"
"                });\n"
"        }\n"
"        \n"
"        function undoLastStep() {\n"
"            if (stepCount <= 0) {\n"
"                document.getElementById('sequence-status').textContent = '⚠️ 没有可撤回的步骤';\n"
"                document.getElementById('sequence-status').style.color = '#f39c12';\n"
"                return;\n"
"            }\n"
"            \n"
"            fetch('/sequence/undo')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (data.success) {\n"
"                        stepCount = data.frame_count || Math.max(0, stepCount - 1);\n"
"                        updateRecordingUI();\n"
"                        document.getElementById('sequence-status').textContent = '↩️ 已撤回上一步';\n"
"                        document.getElementById('sequence-status').style.color = '#7f8c8d';\n"
"                        loadSequenceSteps();\n"
"                    } else {\n"
"                        document.getElementById('sequence-status').textContent = '❌ ' + data.message;\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    }\n"
"                });\n"
"        }\n"
"        \n"
"        function setDefaultSequence() {\n"
"            if (confirm('设置默认开合序列（120°↔150°，5秒间隔）？这将清空现有序列。')) {\n"
"                fetch('/sequence/default')\n"
"                    .then(response => response.json())\n"
"                    .then(data => {\n"
"                        if (data.success) {\n"
"                            stepCount = data.frame_count || 0;\n"
"                            updateRecordingUI();\n"
"                            document.getElementById('sequence-status').textContent = '🔄 默认序列已设置';\n"
"                            document.getElementById('sequence-status').style.color = '#9b59b6';\n"
"                            loadSequenceSteps();\n"
"                        } else {\n"
"                            document.getElementById('sequence-status').textContent = '❌ ' + data.message;\n"
"                            document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                        }\n"
"                    });\n"
"            }\n"
"        }\n"
"        \n"
"        function clearAllSteps() {\n"
"            if (confirm('确定要清空所有序列步骤吗？')) {\n"
"                fetch('/sequence/clear')\n"
"                    .then(response => response.json())\n"
"                    .then(data => {\n"
"                        if (data.success) {\n"
"                            stepCount = 0;\n"
"                            updateRecordingUI();\n"
"                            document.getElementById('sequence-status').textContent = '🗑️ 序列已清空';\n"
"                            document.getElementById('sequence-status').style.color = '#7f8c8d';\n"
"                            loadSequenceSteps();\n"
"                        } else {\n"
"                            document.getElementById('sequence-status').textContent = '❌ ' + data.message;\n"
"                            document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                        }\n"
"                    });\n"
"            }\n"
"        }\n"
"        \n"
"        function playSequence() {\n"
"            fetch('/sequence/play')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (data.success) {\n"
"                        document.getElementById('sequence-status').textContent = '▶️ 序列播放中...';\n"
"                        document.getElementById('sequence-status').style.color = '#3498db';\n"
"                    } else {\n"
"                        document.getElementById('sequence-status').textContent = '❌ ' + data.message;\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    }\n"
"                });\n"
"        }\n"
"        \n"
"        function stopPlaySequence() {\n"
"            fetch('/sequence/stop_play')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (data.success) {\n"
"                        document.getElementById('sequence-status').textContent = '⏹️ 播放已停止';\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    } else {\n"
"                        document.getElementById('sequence-status').textContent = '❌ ' + data.message;\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    }\n"
"                });\n"
"        }\n"
"        \n"
"        function loadSequenceSteps() {\n"
"            fetch('/sequence/steps')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    const stepsList = document.getElementById('steps-list');\n"
"                    if (data.success && data.steps && data.steps.length > 0) {\n"
"                        let html = '';\n"
"                        data.steps.forEach((step, index) => {\n"
"                            html += `步骤 ${index + 1}: L=${step.left_angle}°, R=${step.right_angle}°`;\n"
"                            if (step.delay_ms > 0) {\n"
"                                html += ` (间隔${step.delay_ms}ms)`;\n"
"                            }\n"
"                            html += '<br>';\n"
"                        });\n"
"                        stepsList.innerHTML = html;\n"
"                    } else {\n"
"                        stepsList.textContent = '暂无步骤';\n"
"                    }\n"
"                });\n"
"        }\n"
"    </script>\n"
"</body>\n"
"</html>";

// HTTP处理器函数
esp_err_t handle_robot_sequence_get_handler(httpd_req_t *req) {
    httpd_resp_set_type(req, "text/html");
    httpd_resp_send(req, robot_sequence_html, HTTPD_RESP_USE_STRLEN);
    return ESP_OK;
}

// 注册机器人编程界面处理器（同时注册根路径和/robot路径）
void register_robot_sequence_handler(httpd_handle_t server) {
    // 根路径处理器
    httpd_uri_t index_uri = {
        .uri       = "/",
        .method    = HTTP_GET,
        .handler   = handle_robot_sequence_get_handler,
        .user_ctx  = NULL
    };
    httpd_register_uri_handler(server, &index_uri);
    
    // /robot 路径处理器
    httpd_uri_t robot_sequence_uri = {
        .uri       = "/robot",
        .method    = HTTP_GET,
        .handler   = handle_robot_sequence_get_handler,
        .user_ctx  = NULL
    };
    httpd_register_uri_handler(server, &robot_sequence_uri);
    
    ESP_LOGI(TAG, "Registered / and /robot handlers");
}