#include "http_server_ux_enhanced.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "string.h"

static const char *TAG = "http_server_files";

// 完整的移动端优化HTML - 包含序列录制功能
static const char complete_mobile_html[] = 
"<!DOCTYPE html>\n"
"<html lang=\"zh-CN\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n"
"    <title>翅膀控制系统</title>\n"
"    <style>\n"
"        * {box-sizing: border-box;}\n"
"        body {font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, sans-serif; margin: 0; padding: 15px; background-color: #fff34d; color: #333; -webkit-touch-callout: none; -webkit-user-select: none; -khtml-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; font-size: 14px; line-height: 1.4;}\n"
"        .container {max-width: 1080px; margin: 0 auto;}\n"
"        h1 {text-align: center; color: #2c3e50; margin-bottom: 20px; font-size: 24px; font-weight: bold;}\n"
"        .section {background: white; border-radius: 12px; padding: 16px; margin-bottom: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);}\n"
"        .section-title {font-size: 18px; font-weight: bold; margin-bottom: 12px; color: #2c3e50; text-align: center;}\n"
"        .control-group {margin-bottom: 12px;}\n"
"        label {display: block; margin-bottom: 6px; font-weight: bold; color: #2c3e50; font-size: 14px;}\n"
"        input[type=\"range\"] {width: 100%; height: 8px; border-radius: 4px; background: #ddd; outline: none; -webkit-appearance: none; margin: 4px 0;}\n"
"        input[type=\"range\"]::-webkit-slider-thumb {-webkit-appearance: none; width: 22px; height: 22px; border-radius: 50%; background: #3498db; cursor: pointer; box-shadow: 0 1px 3px rgba(0,0,0,0.2);}\n"
"        input[type=\"number\"] {width: 100%; padding: 8px; border: 2px solid #ddd; border-radius: 8px; font-size: 14px;}\n"
"        .angle-display {display: flex; justify-content: space-between; margin-top: 4px; font-size: 12px; color: #2c3e50;}\n"
"        .current-indicator {height: 3px; background: #2ecc71; border-radius: 2px; margin-top: 6px; position: relative;}\n"
"        .current-indicator::before {content: ''; position: absolute; right: 0; top: 0; height: 100%; background: #ecf0f1;}\n"
"        .button-group {display: flex; gap: 8px; flex-wrap: wrap; margin: 8px 0;}\n"
"        button {flex: 1; min-width: 70px; padding: 10px; border: none; border-radius: 20px; background: #3498db; color: white; font-weight: bold; cursor: pointer; transition: all 0.2s; font-size: 13px; touch-action: manipulation; -webkit-tap-highlight-color: transparent;}\n"
"        button:hover {background: #2980b9; transform: translateY(-1px);}\n"
"        button:active {transform: translateY(0);}\n"
"        .motor-button {background: #e74c3c;}\n"
"        .motor-button:hover {background: #c0392b;}\n"
"        .sequence-button {background: #9b59b6;}\n"
"        .sequence-button:hover {background: #8e44ad;}\n"
"        .record-button {background: #e67e22;}\n"
"        .record-button:hover {background: #d35400;}\n"
"        .feedback {margin-top: 8px; padding: 6px; border-radius: 6px; text-align: center; font-weight: bold; font-size: 13px;}\n"
"        .slider-container {margin-bottom: 12px;}\n"
"        .single-slider-container {text-align: center;}\n"
"        .single-slider-label {font-size: 15px; font-weight: bold; margin-bottom: 8px; color: #2c3e50;}\n"
"        .single-angle-display {display: flex; justify-content: center; align-items: center; gap: 15px; margin-top: 8px;}\n"
"        .angle-value {font-size: 16px; font-weight: bold; color: #2c3e50;}\n"
"        .hidden {display: none !important;}\n"
"        .switch-container {display: flex; align-items: center; justify-content: center; gap: 8px; margin: 12px 0;}\n"
"        .switch-label {font-weight: bold; color: #2c3e50; font-size: 14px;}\n"
"        .sequence-info {margin-top: 8px; font-size: 12px; color: #7f8c8d; text-align: center;}\n"
"        \n"
"        /* 移动端优化 */\n"
"        @media (max-width: 480px) {\n"
"            body {padding: 10px; font-size: 13px;}\n"
"            h1 {font-size: 20px; margin-bottom: 15px;}\n"
"            .section {padding: 12px; margin-bottom: 15px;}\n"
"            .section-title {font-size: 16px; margin-bottom: 10px;}\n"
"            button {padding: 8px; min-width: 60px; font-size: 12px;}\n"
"            input[type=\"number\"] {padding: 6px; font-size: 13px;}\n"
"            .angle-value {font-size: 14px;}\n"
"            .single-slider-label {font-size: 14px; margin-bottom: 6px;}\n"
"        }\n"
"        \n"
"        /* 触摸设备优化 */\n"
"        @media (hover: none) and (pointer: coarse) {\n"
"            input[type=\"range\"]::-webkit-slider-thumb {width: 26px; height: 26px;}\n"
"            button {padding: 12px; min-height: 44px;}\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <h1>🦋 翅膀控制系统</h1>\n"
"        \n"
"        <!-- 控制设置 -->\n"
"        <div class=\"section\">\n"
"            <div class=\"section-title\">⚙️ 控制设置</div>\n"
"            \n"
"            <div class=\"control-group\">\n"
"                <label for=\"min-angle\">最小角度限制 (°)</label>\n"
"                <input type=\"number\" id=\"min-angle\" value=\"120\" min=\"0\" max=\"270\">\n"
"            </div>\n"
"            \n"
"            <div class=\"control-group\">\n"
"                <label for=\"max-angle\">最大角度限制 (°)</label>\n"
"                <input type=\"number\" id=\"max-angle\" value=\"150\" min=\"0\" max=\"270\">\n"
"            </div>\n"
"            \n"
"            <button onclick=\"updateAngleLimits()\" style=\"background: #27ae60;\">更新角度限制</button>\n"
"            <div id=\"limits-feedback\" class=\"feedback\"></div>\n"
"            \n"
"            <div class=\"switch-container\">\n"
"                <span class=\"switch-label\">左右对称控制:</span>\n"
"                <label class=\"switch\">\n"
"                    <input type=\"checkbox\" id=\"symmetric-lock\" checked onchange=\"toggleSymmetricMode()\">\n"
"                </label>\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <!-- 舵机控制 - 双滑条模式 -->\n"
"        <div class=\"section\" id=\"dual-servo-control\">\n"
"            <div class=\"section-title\">🦾 舵机控制 (独立)</div>\n"
"            \n"
"            <!-- 左侧舵机 -->\n"
"            <div class=\"slider-container\">\n"
"                <label>左侧翅膀角度</label>\n"
"                <input type=\"range\" id=\"left-servo\" min=\"120\" max=\"150\" value=\"135\" oninput=\"updateDualAngle('left')\">\n"
"                <div class=\"angle-display\">\n"
"                    <span id=\"left-range\">120° - 150°</span>\n"
"                    <span id=\"left-angle-value\">135°</span>\n"
"                </div>\n"
"                <div class=\"current-indicator\" id=\"left-current\">\n"
"                    <div id=\"left-current-fill\" style=\"width: 50%;\"></div>\n"
"                </div>\n"
"                \n"
"                <div class=\"control-group\" style=\"margin-top: 8px;\">\n"
"                    <label for=\"left-speed\">左侧速度 (ms)</label>\n"
"                    <input type=\"number\" id=\"left-speed\" value=\"100\" min=\"0\" max=\"9999\" onchange=\"updateDualSpeed('left')\">\n"
"                </div>\n"
"            </div>\n"
"            \n"
"            <!-- 右侧舵机 -->\n"
"            <div class=\"slider-container\">\n"
"                <label>右侧翅膀角度</label>\n"
"                <input type=\"range\" id=\"right-servo\" min=\"120\" max=\"150\" value=\"135\" oninput=\"updateDualAngle('right')\">\n"
"                <div class=\"angle-display\">\n"
"                    <span id=\"right-range\">120° - 150°</span>\n"
"                    <span id=\"right-angle-value\">135°</span>\n"
"                </div>\n"
"                <div class=\"current-indicator\" id=\"right-current\">\n"
"                    <div id=\"right-current-fill\" style=\"width: 50%;\"></div>\n"
"                </div>\n"
"                \n"
"                <div class=\"control-group\" style=\"margin-top: 8px;\">\n"
"                    <label for=\"right-speed\">右侧速度 (ms)</label>\n"
"                    <input type=\"number\" id=\"right-speed\" value=\"100\" min=\"0\" max=\"9999\" onchange=\"updateDualSpeed('right')\">\n"
"                </div>\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <!-- 舵机控制 - 单滑条模式 -->\n"
"        <div class=\"section hidden\" id=\"single-servo-control\">\n"
"            <div class=\"section-title\">🦾 舵机控制 (对称)</div>\n"
"            \n"
"            <div class=\"single-slider-container\">\n"
"                <div class=\"single-slider-label\">两侧翅膀角度</div>\n"
"                <input type=\"range\" id=\"both-servo\" min=\"120\" max=\"150\" value=\"135\" oninput=\"updateSingleAngle()\">\n"
"                <div class=\"single-angle-display\">\n"
"                    <span id=\"both-range\">120° - 150°</span>\n"
"                    <span class=\"angle-value\" id=\"both-angle-value\">135°</span>\n"
"                </div>\n"
"                <div class=\"current-indicator\" id=\"both-current\">\n"
"                    <div id=\"both-current-fill\" style=\"width: 50%;\"></div>\n"
"                </div>\n"
"            </div>\n"
"            \n"
"            <div class=\"control-group\" style=\"margin-top: 15px;\">\n"
"                <label for=\"both-speed\">两侧速度 (ms)</label>\n"
"                <input type=\"number\" id=\"both-speed\" value=\"100\" min=\"0\" max=\"9999\" onchange=\"updateSingleSpeed()\">\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <!-- 电机控制 -->\n"
"        <div class=\"section\">\n"
"            <div class=\"section-title\">⚡ 电机控制</div>\n"
"            <div class=\"button-group\">\n"
"                <button class=\"motor-button\" onclick=\"motorAction('expand')\">展开翅膀</button>\n"
"                <button class=\"motor-button\" onclick=\"motorAction('close')\">收拢翅膀</button>\n"
"                <button class=\"motor-button\" onclick=\"motorAction('reset')\">重置位置</button>\n"
"                <button class=\"motor-button\" onclick=\"motorAction('stop')\">停止电机</button>\n"
"            </div>\n"
"        </div>\n"
"        \n"
"        <!-- 编程与执行 - 完整录制功能 -->\n"
"        <div class=\"section\">\n"
"            <div class=\"section-title\">🎬 编程与执行</div>\n"
"            \n"
"            <!-- 序列录制控制 -->\n"
"            <div class=\"control-group\">\n"
"                <div class=\"button-group\">\n"
"                    <button class=\"record-button\" onclick=\"startSequenceRecording()\" id=\"record-btn\">▶️ 开始录制</button>\n"
"                    <button class=\"record-button\" onclick=\"saveCurrentStep()\" id=\"save-step-btn\" disabled>💾 保存步骤</button>\n"
"                </div>\n"
"                <div class=\"sequence-info\" id=\"recording-info\">点击\"开始录制\"以启用序列编程</div>\n"
"            </div>\n"
"            \n"
"            <!-- 序列播放控制 -->\n"
"            <div class=\"button-group\">\n"
"                <button class=\"sequence-button\" onclick=\"playSequence()\">▶️ 播放序列</button>\n"
"                <button class=\"sequence-button\" onclick=\"clearSequence()\">🗑️ 清除序列</button>\n"
"            </div>\n"
"            \n"
"            <div id=\"sequence-status\" class=\"feedback\" style=\"margin-top: 8px;\"></div>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"        let minAngle = 120;\n"
"        let maxAngle = 150;\n"
"        let symmetricMode = true;\n"
"        let isRecording = false;\n"
"        let remainingSteps = 0;\n"
"        \n"
"        function init() {\n"
"            updateSliderRanges();\n"
"            toggleSymmetricMode();\n"
"            updateRecordingUI();\n"
"        }\n"
"        \n"
"        function updateSliderRanges() {\n"
"            const sliders = ['left-servo', 'right-servo', 'both-servo'];\n"
"            sliders.forEach(id => {\n"
"                const slider = document.getElementById(id);\n"
"                if (slider) {\n"
"                    slider.min = minAngle;\n"
"                    slider.max = maxAngle;\n"
"                    const currentValue = parseInt(slider.value);\n"
"                    if (currentValue < minAngle) slider.value = minAngle;\n"
"                    if (currentValue > maxAngle) slider.value = maxAngle;\n"
"                }\n"
"            });\n"
"            \n"
"            document.getElementById('left-range').textContent = minAngle + '° - ' + maxAngle + '°';\n"
"            document.getElementById('right-range').textContent = minAngle + '° - ' + maxAngle + '°';\n"
"            document.getElementById('both-range').textContent = minAngle + '° - ' + maxAngle + '°';\n"
"            \n"
"            updateAngleDisplays();\n"
"        }\n"
"        \n"
"        function updateAngleLimits() {\n"
"            const newMin = parseInt(document.getElementById('min-angle').value);\n"
"            const newMax = parseInt(document.getElementById('max-angle').value);\n"
"            \n"
"            if (newMin >= 0 && newMin <= 270 && newMax >= 0 && newMax <= 270 && newMin < newMax) {\n"
"                minAngle = newMin;\n"
"                maxAngle = newMax;\n"
"                updateSliderRanges();\n"
"                fetch('/set_limits?min=' + minAngle + '&max=' + maxAngle)\n"
"                    .then(() => {\n"
"                        document.getElementById('limits-feedback').textContent = '✓ 角度范围已更新: ' + minAngle + '° - ' + maxAngle + '°';\n"
"                        document.getElementById('limits-feedback').style.color = '#27ae60';\n"
"                    });\n"
"            } else {\n"
"                document.getElementById('limits-feedback').textContent = '❌ 角度范围无效！';\n"
"                document.getElementById('limits-feedback').style.color = '#e74c3c';\n"
"                document.getElementById('min-angle').value = minAngle;\n"
"                document.getElementById('max-angle').value = maxAngle;\n"
"            }\n"
"        }\n"
"        \n"
"        function toggleSymmetricMode() {\n"
"            symmetricMode = document.getElementById('symmetric-lock').checked;\n"
"            \n"
"            if (symmetricMode) {\n"
"                document.getElementById('dual-servo-control').classList.add('hidden');\n"
"                document.getElementById('single-servo-control').classList.remove('hidden');\n"
"                \n"
"                const leftValue = parseInt(document.getElementById('left-servo').value);\n"
"                document.getElementById('both-servo').value = leftValue;\n"
"                document.getElementById('both-angle-value').textContent = leftValue + '°';\n"
"                document.getElementById('both-speed').value = document.getElementById('left-speed').value;\n"
"                \n"
"                const speed = parseInt(document.getElementById('both-speed').value);\n"
"                fetch('/set_servo?servo_id=0&angle=' + leftValue + '&speed=' + speed);\n"
"                fetch('/set_servo?servo_id=1&angle=' + leftValue + '&speed=' + speed);\n"
"                fetch('/set_symmetric?locked=1');\n"
"            } else {\n"
"                document.getElementById('single-servo-control').classList.add('hidden');\n"
"                document.getElementById('dual-servo-control').classList.remove('hidden');\n"
"                \n"
"                const bothValue = parseInt(document.getElementById('both-servo').value);\n"
"                document.getElementById('left-servo').value = bothValue;\n"
"                document.getElementById('right-servo').value = bothValue;\n"
"                document.getElementById('left-angle-value').textContent = bothValue + '°';\n"
"                document.getElementById('right-angle-value').textContent = bothValue + '°';\n"
"                document.getElementById('left-speed').value = document.getElementById('both-speed').value;\n"
"                document.getElementById('right-speed').value = document.getElementById('both-speed').value;\n"
"                \n"
"                fetch('/set_symmetric?locked=0');\n"
"            }\n"
"            \n"
"            updateAngleDisplays();\n"
"        }\n"
"        \n"
"        function updateAngleDisplays() {\n"
"            if (symmetricMode) {\n"
"                const bothValue = document.getElementById('both-servo').value;\n"
"                document.getElementById('both-angle-value').textContent = bothValue + '°';\n"
"            } else {\n"
"                const leftValue = document.getElementById('left-servo').value;\n"
"                const rightValue = document.getElementById('right-servo').value;\n"
"                document.getElementById('left-angle-value').textContent = leftValue + '°';\n"
"                document.getElementById('right-angle-value').textContent = rightValue + '°';\n"
"            }\n"
"        }\n"
"        \n"
"        function updateSingleAngle() {\n"
"            const angle = parseInt(document.getElementById('both-servo').value);\n"
"            const speed = parseInt(document.getElementById('both-speed').value);\n"
"            \n"
"            fetch('/set_servo?servo_id=0&angle=' + angle + '&speed=' + speed);\n"
"            fetch('/set_servo?servo_id=1&angle=' + angle + '&speed=' + speed);\n"
"            \n"
"            document.getElementById('both-angle-value').textContent = angle + '°';\n"
"        }\n"
"        \n"
"        function updateSingleSpeed() {\n"
"            const angle = parseInt(document.getElementById('both-servo').value);\n"
"            const speed = parseInt(document.getElementById('both-speed').value);\n"
"            \n"
"            fetch('/set_servo?servo_id=0&angle=' + angle + '&speed=' + speed);\n"
"            fetch('/set_servo?servo_id=1&angle=' + angle + '&speed=' + speed);\n"
"        }\n"
"        \n"
"        function updateDualAngle(side) {\n"
"            const slider = document.getElementById(side + '-servo');\n"
"            const angle = parseInt(slider.value);\n"
"            const speed = parseInt(document.getElementById(side + '-speed').value);\n"
"            const servoId = side === 'left' ? 0 : 1;\n"
"            \n"
"            fetch('/set_servo?servo_id=' + servoId + '&angle=' + angle + '&speed=' + speed);\n"
"            document.getElementById(side + '-angle-value').textContent = angle + '°';\n"
"        }\n"
"        \n"
"        function updateDualSpeed(side) {\n"
"            const angle = parseInt(document.getElementById(side + '-servo').value);\n"
"            const speed = parseInt(document.getElementById(side + '-speed').value);\n"
"            const servoId = side === 'left' ? 0 : 1;\n"
"            \n"
"            fetch('/set_servo?servo_id=' + servoId + '&angle=' + angle + '&speed=' + speed);\n"
"        }\n"
"        \n"
"        function updateCurrentIndicator(side, currentAngle) {\n"
"            const indicatorFill = document.getElementById(side + '-current-fill');\n"
"            if (!indicatorFill) return;\n"
"            \n"
"            if (currentAngle < 0) {\n"
"                indicatorFill.style.width = '0%';\n"
"                return;\n"
"            }\n"
"            \n"
"            const range = maxAngle - minAngle;\n"
"            if (range <= 0) return;\n"
"            \n"
"            let percentage = ((currentAngle - minAngle) / range) * 100;\n"
"            percentage = Math.max(0, Math.min(100, percentage));\n"
"            indicatorFill.style.width = percentage + '%';\n"
"        }\n"
"        \n"
"        function motorAction(action) {\n"
"            fetch('/motor?action=' + action);\n"
"        }\n"
"        \n"
"        function updateRecordingUI() {\n"
"            const recordBtn = document.getElementById('record-btn');\n"
"            const saveBtn = document.getElementById('save-step-btn');\n"
"            const infoDiv = document.getElementById('recording-info');\n"
"            \n"
"            if (isRecording) {\n"
"                recordBtn.textContent = '⏹️ 停止录制';\n"
"                recordBtn.style.background = '#e74c3c';\n"
"                saveBtn.disabled = false;\n"
"                infoDiv.textContent = `录制中... 还可添加 ${remainingSteps} 步`;\n"
"                infoDiv.style.color = '#e67e22';\n"
"            } else {\n"
"                recordBtn.textContent = '▶️ 开始录制';\n"
"                recordBtn.style.background = '#e67e22';\n"
"                saveBtn.disabled = true;\n"
"                infoDiv.textContent = '点击\"开始录制\"以启用序列编程';\n"
"                infoDiv.style.color = '#7f8c8d';\n"
"            }\n"
"        }\n"
"        \n"
"        function startSequenceRecording() {\n"
"            if (!isRecording) {\n"
"                fetch('/sequence/start')\n"
"                    .then(response => response.json())\n"
"                    .then(data => {\n"
"                        if (data.success && data.remaining_steps >= 0) {\n"
"                            isRecording = true;\n"
"                            remainingSteps = data.remaining_steps;\n"
"                            updateRecordingUI();\n"
"                            document.getElementById('sequence-status').textContent = '✅ 录制模式已启用';\n"
"                            document.getElementById('sequence-status').style.color = '#e67e22';\n"
"                        } else {\n"
"                            document.getElementById('sequence-status').textContent = '❌ 无法启动录制: ' + (data.message || '未知错误');\n"
"                            document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                        }\n"
"                    })\n"
"                    .catch(error => {\n"
"                        document.getElementById('sequence-status').textContent = '❌ 录制启动失败';\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    });\n"
"            } else {\n"
"                isRecording = false;\n"
"                updateRecordingUI();\n"
"                document.getElementById('sequence-status').textContent = '⏹️ 录制已停止';\n"
"                document.getElementById('sequence-status').style.color = '#7f8c8d';\n"
"            }\n"
"        }\n"
"        \n"
"        function saveCurrentStep() {\n"
"            if (!isRecording || remainingSteps <= 0) {\n"
"                document.getElementById('sequence-status').textContent = '⚠️ 无法保存步骤';\n"
"                document.getElementById('sequence-status').style.color = '#f39c12';\n"
"                return;\n"
"            }\n"
"            \n"
"            let leftAngle, rightAngle;\n"
"            if (symmetricMode) {\n"
"                leftAngle = parseInt(document.getElementById('both-servo').value);\n"
"                rightAngle = leftAngle;\n"
"            } else {\n"
"                leftAngle = parseInt(document.getElementById('left-servo').value);\n"
"                rightAngle = parseInt(document.getElementById('right-servo').value);\n"
"            }\n"
"            \n"
"            fetch(`/sequence/save?left=${leftAngle}&right=${rightAngle}`)\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (data.success) {\n"
"                        remainingSteps = data.remaining_steps;\n"
"                        updateRecordingUI();\n"
"                        document.getElementById('sequence-status').textContent = `✅ 步骤已保存! 还剩 ${remainingSteps} 步`;\n"
"                        document.getElementById('sequence-status').style.color = '#27ae60';\n"
"                    } else {\n"
"                        document.getElementById('sequence-status').textContent = '❌ 保存失败: ' + (data.message || '未知错误');\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    }\n"
"                })\n"
"                .catch(error => {\n"
"                    document.getElementById('sequence-status').textContent = '❌ 保存步骤失败';\n"
"                    document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                });\n"
"        }\n"
"        \n"
"        function playSequence() {\n"
"            fetch('/sequence/play')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (data.success) {\n"
"                        document.getElementById('sequence-status').textContent = '✅ 序列播放中...';\n"
"                        document.getElementById('sequence-status').style.color = '#27ae60';\n"
"                    } else {\n"
"                        document.getElementById('sequence-status').textContent = '❌ 播放失败: ' + data.message;\n"
"                        document.getElementById('sequence-status').style.color = '#e74c3c';\n"
"                    }\n"
"                });\n"
"        }\n"
"        \n"
"        function clearSequence() {\n"
"            if (confirm('确定要清除所有序列步骤吗？')) {\n"
"                fetch('/sequence/clear')\n"
"                    .then(() => {\n"
"                        isRecording = false;\n"
"                        remainingSteps = 0;\n"
"                        updateRecordingUI();\n"
"                        document.getElementById('sequence-status').textContent = '🗑️ 序列已清除';\n"
"                        document.getElementById('sequence-status').style.color = '#7f8c8d';\n"
"                    });\n"
"            }\n"
"        }\n"
"        \n"
"        setInterval(() => {\n"
"            fetch('/get_angles')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    if (symmetricMode) {\n"
"                        updateCurrentIndicator('both', data.left);\n"
"                    } else {\n"
"                        updateCurrentIndicator('left', data.left);\n"
"                        updateCurrentIndicator('right', data.right);\n"
"                    }\n"
"                })\n"
"                .catch(error => {\n"
"                    if (symmetricMode) {\n"
"                        updateCurrentIndicator('both', -1);\n"
"                    } else {\n"
"                        updateCurrentIndicator('left', -1);\n"
"                        updateCurrentIndicator('right', -1);\n"
"                    }\n"
"                });\n"
"        }, 500);\n"
"        \n"
"        document.addEventListener('DOMContentLoaded', init);\n"
"    </script>\n"
"</body>\n"
"</html>";

// Favicon handler to prevent 404 errors
static esp_err_t favicon_handler(httpd_req_t *req) {
    httpd_resp_set_status(req, "204 No Content");
    httpd_resp_send(req, NULL, 0);
    return ESP_OK;
}

// Main page handler
static esp_err_t index_handler(httpd_req_t *req) {
    httpd_resp_set_type(req, "text/html");
    httpd_resp_set_hdr(req, "Cache-Control", "no-cache");
    return httpd_resp_send(req, complete_mobile_html, strlen(complete_mobile_html));
}

// Register file handlers - this function is declared in http_server_ux_enhanced.h
void register_file_handlers(httpd_handle_t server) {
    httpd_uri_t favicon_uri = {
        .uri       = "/favicon.ico",
        .method    = HTTP_GET,
        .handler   = favicon_handler,
        .user_ctx  = NULL
    };
    
    httpd_uri_t index_uri = {
        .uri       = "/",
        .method    = HTTP_GET,
        .handler   = index_handler,
        .user_ctx  = NULL
    };
    
    httpd_register_uri_handler(server, &favicon_uri);
    httpd_register_uri_handler(server, &index_uri);
}